name: eeg2025
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pytorch>=2.0.0
  - torchvision
  - torchaudio
  - numpy
  - scipy
  - pandas
  - scikit-learn
  - matplotlib
  - seaborn
  - jupyter
  - tqdm
  - pip
  - pip:
    - mne>=1.5.0
    - mne-bids>=0.13
    - braindecode>=0.8.0
    - moabb>=0.5.0
    - gdown
    - wandb  # Optional: for experiment tracking
